# Generated by Django 3.1.3 on 2020-12-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=300)),
                ('slug', models.SlugField()),
                ('article_text', models.TextField()),
                ('author', models.CharField(max_length=50)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
